//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HazrefSampleEntities : DbContext
    {
        public HazrefSampleEntities()
            : base("name=HazrefSampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentBanner> ContentBanner { get; set; }
        public virtual DbSet<ContentLocale> ContentLocale { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsImage> NewsImage { get; set; }
        public virtual DbSet<NewsLocale> NewsLocale { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<PageFile> PageFile { get; set; }
        public virtual DbSet<PageFileLocale> PageFileLocale { get; set; }
        public virtual DbSet<PageLocale> PageLocale { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<PageLocaleForIntegration> PageLocaleForIntegration { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
    }
}
