//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facade
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImage
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
