//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace durer2.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("durer2.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKINDA.
        /// </summary>
        public static string AboutUpper {
            get {
                return ResourceManager.GetString("AboutUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTAJ.
        /// </summary>
        public static string AssemblyUpper {
            get {
                return ResourceManager.GetString("AssemblyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuğlalar.
        /// </summary>
        public static string Bricks {
            get {
                return ResourceManager.GetString("Bricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KATALOG.
        /// </summary>
        public static string CatalogUpper {
            get {
                return ResourceManager.GetString("CatalogUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /katalog.
        /// </summary>
        public static string CatalogUrl {
            get {
                return ResourceManager.GetString("CatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇİMENTO SEKTÖRÜ.
        /// </summary>
        public static string CementUpper {
            get {
                return ResourceManager.GetString("CementUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÜŞTERİ AĞI.
        /// </summary>
        public static string ClientNetworkUpper {
            get {
                return ResourceManager.GetString("ClientNetworkUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket:.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KURUMSAL.
        /// </summary>
        public static string CompanyUpper {
            get {
                return ResourceManager.GetString("CompanyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANIŞMANLIK.
        /// </summary>
        public static string ConsultancyUpper {
            get {
                return ResourceManager.GetString("ConsultancyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu Kişi:.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string ContactUpper {
            get {
                return ResourceManager.GetString("ContactUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /iletisim.
        /// </summary>
        public static string ContactUrl {
            get {
                return ResourceManager.GetString("ContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haznedar Refrakter ve Durer Monolitik, Haznedar Durer Refrakter adı altında tek bir şirket yapısında buluştu ve Calderys ile güçlerini birleştirdi. Birlikte, yüksek kalite refrakter tuğla ve monolitik ürünlerimiz ile çok yüksek sıcaklıklar ve ağır koşullarda faaliyetlerini yürüten sektörlerin en güçlü çözüm ortağı olmaya devam edeceğiz..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KURUTMA VE ISITMA.
        /// </summary>
        public static string DryingUpper {
            get {
                return ResourceManager.GetString("DryingUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to durer-refrakter.png.
        /// </summary>
        public static string DurerLogoUrl {
            get {
                return ResourceManager.GetString("DurerLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM SEKTÖRÜ.
        /// </summary>
        public static string GlassUpper {
            get {
                return ResourceManager.GetString("GlassUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haznedar-refrakter.png.
        /// </summary>
        public static string HaznedarLogoUrl {
            get {
                return ResourceManager.GetString("HaznedarLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİHÇE.
        /// </summary>
        public static string HistoryUpper {
            get {
                return ResourceManager.GetString("HistoryUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websitesi:.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANA SAYFA.
        /// </summary>
        public static string HomeUpper {
            get {
                return ResourceManager.GetString("HomeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNSAN KAYNAKLARI POLİTİKASI.
        /// </summary>
        public static string HrPolicyUpper {
            get {
                return ResourceManager.GetString("HrPolicyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNSAN KAYNAKLARI.
        /// </summary>
        public static string HrUpper {
            get {
                return ResourceManager.GetString("HrUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEKTÖRLER.
        /// </summary>
        public static string IndustriesUpper {
            get {
                return ResourceManager.GetString("IndustriesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİ TOPLUMU HİZMETLERİ.
        /// </summary>
        public static string InformationUpper {
            get {
                return ResourceManager.GetString("InformationUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YATIRIMCI İLİŞKİLERİ.
        /// </summary>
        public static string InvestorUpper {
            get {
                return ResourceManager.GetString("InvestorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMİR ÇELİK SEKTÖRÜ.
        /// </summary>
        public static string IronSteelUpper {
            get {
                return ResourceManager.GetString("IronSteelUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KİREÇ SEKTÖRÜ.
        /// </summary>
        public static string LimeUpper {
            get {
                return ResourceManager.GetString("LimeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo.png.
        /// </summary>
        public static string LogoUrl {
            get {
                return ResourceManager.GetString("LogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKIM.
        /// </summary>
        public static string MaintenanceUpper {
            get {
                return ResourceManager.GetString("MaintenanceUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VİZYON VE TAAHHÜT.
        /// </summary>
        public static string MissionVisionUpper {
            get {
                return ResourceManager.GetString("MissionVisionUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monolitik ve Dökme Betonlar.
        /// </summary>
        public static string Monolotics {
            get {
                return ResourceManager.GetString("Monolotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        public static string NewsUpper {
            get {
                return ResourceManager.GetString("NewsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /haberler.
        /// </summary>
        public static string NewsUrl {
            get {
                return ResourceManager.GetString("NewsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMİR DIŞI METALURJİ SEKTÖRÜ.
        /// </summary>
        public static string NonferrousUpper {
            get {
                return ResourceManager.GetString("NonferrousUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞERLERİ.
        /// </summary>
        public static string OthersUpper {
            get {
                return ResourceManager.GetString("OthersUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETLER.
        /// </summary>
        public static string OurServicesUpper {
            get {
                return ResourceManager.GetString("OurServicesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETROKİMYA TESİSLERİ VE RAFİNERİLER.
        /// </summary>
        public static string PetroUpper {
            get {
                return ResourceManager.GetString("PetroUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIK POZİSYONLAR.
        /// </summary>
        public static string PositionsUpper {
            get {
                return ResourceManager.GetString("PositionsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIN.
        /// </summary>
        public static string PressUpper {
            get {
                return ResourceManager.GetString("PressUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /basin.
        /// </summary>
        public static string PressUrl {
            get {
                return ResourceManager.GetString("PressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN GRUPLARI &amp; KALİTELER.
        /// </summary>
        public static string ProductGradesUpper {
            get {
                return ResourceManager.GetString("ProductGradesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİM AKIŞI.
        /// </summary>
        public static string ProductionFlowUpper {
            get {
                return ResourceManager.GetString("ProductionFlowUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string ProductsUpper {
            get {
                return ResourceManager.GetString("ProductsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJE MÜHENDİSLİĞİ.
        /// </summary>
        public static string ProjectEngUpper {
            get {
                return ResourceManager.GetString("ProjectEngUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERTİFİKALAR.
        /// </summary>
        public static string QualityCertificateUpper {
            get {
                return ResourceManager.GetString("QualityCertificateUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAMMADDE TEDARİĞİ.
        /// </summary>
        public static string RawMaterialUpper {
            get {
                return ResourceManager.GetString("RawMaterialUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN REÇETESİ İSTEK FORMU.
        /// </summary>
        public static string RequestFormUpper {
            get {
                return ResourceManager.GetString("RequestFormUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektör:.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /hizmetler.
        /// </summary>
        public static string ServicesUrl {
            get {
                return ResourceManager.GetString("ServicesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOSYAL SORUMLULUK.
        /// </summary>
        public static string SocialResponsibilityUpper {
            get {
                return ResourceManager.GetString("SocialResponsibilityUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDART TUĞLA ŞEKİLLERİ VE ÖLÇÜLERİ.
        /// </summary>
        public static string StandartBrickUpper {
            get {
                return ResourceManager.GetString("StandartBrickUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız gönderildi..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SÜPERVİZÖRLÜK.
        /// </summary>
        public static string SupervisoryUpper {
            get {
                return ResourceManager.GetString("SupervisoryUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEDARİKÇİ KAYIT FORMU.
        /// </summary>
        public static string SupplierFormUpper {
            get {
                return ResourceManager.GetString("SupplierFormUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvan:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULLANIM ALANLARI.
        /// </summary>
        public static string UsageUpper {
            get {
                return ResourceManager.GetString("UsageUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEĞERLERİMİZ.
        /// </summary>
        public static string ValuesUpper {
            get {
                return ResourceManager.GetString("ValuesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATIK YAKMA TESİSLERİ.
        /// </summary>
        public static string WasteUpper {
            get {
                return ResourceManager.GetString("WasteUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
